# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile/')),
                ('name', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('bio', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=140)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
